---
- name: Install OpenClaw
  ansible.builtin.include_tasks: install.yml

- name: Patch heartbeat group delivery bug
  ansible.builtin.include_tasks: patch-heartbeat-group-fix.yml

- name: Onboard OpenClaw
  ansible.builtin.include_tasks: onboard.yml

- name: Install OpenClaw daemon
  ansible.builtin.include_tasks: daemon.yml
